### ISSUE TITLE
FEAT: Grant access to multiple repos / entire org

### ISSUE THREAD

**Issue by NickCrews** [qoomon/github-actions-access-manager#3]
I have many private repos in an org: org/A, org/B, org/C. I want to let B and C have access to A.

Currently, I have to list B and C explicitly in A's permissions file. I would like to be able to say "make these permissions apply to all repos under `org/`".

Perhaps a glob pattern works? eg 
```
self: org/A
policies:
- repository: org/*
  permissions:
    packages: read
```

not sure if a literal `*` is a valid character in org or repo names, if so then this would be a problem.

Or more clunky, but more flexible, could also supply a list

```yaml
self: org/A
policies:
- repository:
    # All these ar ORed together
    - org/B
    - org/C
    - org/more-selective-pattern-*
  permissions:
    packages: read
```

**Comment by qoomon** [comment]
@NickCrews  Wildcards(`*`) are already supported e.g.
```yaml
self: org/A
policies:
- repository: org/*
  permissions:
    packages: read
```

However I should describe that feature in the README 😅
