### ISSUE TITLE
FEAT: One token for access to multiple repos

### ISSUE THREAD

**Issue by NickCrews** [qoomon/github-actions-access-manager#4]
Related to #3, but in the other direction. I have one repo X, that needs access to both Y and Z. It would be great to request access to both of these in a single step and get one token that works for both. For instance, if with python I do `pip install Y Z`, git will need permission to both Y and Z at the same time

```yaml
# .github/workflows/CI.yaml in org/X
      - uses: qoomon/github-actions-access-manager@v1
        id: github-actions-access
        with:
          repository:
            - org/Y
            - org/Z
            # Using org/* doesn't make as much sense here? Perhaps for more complex config this
            # could also go in org/X's access.yaml ?
        - name: Use the one token to access all repos at the same time
          run: |
            # Really I have these git depencies stored in a requirements.txt, but this gets the point across.
            pip install git+https://github.com/org/Y.git git+https://github.com/org/Z.git
```

**Comment by qoomon** [comment]
I'm not sure if this is possible, however I'll investigate.

**Comment by qoomon** [comment]
It seems to be possible to generate one token with access to multiple repositories, only restriction is all repositories need to belong to same organisation or user e.g. foo/A, foo/B, ...

**Comment by qoomon** [comment]
A wildcard access token for foo/* is not possible in a suitable way, especially not if there more then 100 repositories in on account. So sorry I'll not implementing that.

However I'll implement access tokens for multiple repositories within the same account.

**Comment by NickCrews** [comment]
> However I'll implement access tokens for multiple repositories within the same account.

This is my key use case. One token with access to all repos in one org.

**Comment by qoomon** [comment]
I have a first running version. I'll need to add some further validation and better error handling.

**Comment by qoomon** [comment]
@NickCrews here is my current behavior I want to implement. What do you think?

* **no repos & no permissions**
  * => token with all granted permissions for requesting repo itself
* **no repos & some permissions**
  * => token with requested permissions for requesting repo itself
  * Error in case of requested permissions are not granted
* **some repos & no permissions**
  * token with intersection of all granted permissions for requested repos
* **some repos & some permissions**
  * => token with requested permissions for requested repos
  * Error in case of requested permissions are not granted for all requested repos

In addition I might add the feature to request token for all repos of an owner e.g. `repositories: qoomon/*`, however that would be another feature release.

**Comment by NickCrews** [comment]
> no repos & no permissions
> => token with all granted permissions for requesting repo itself
> no repos & some permissions
>=> token with requested permissions for requesting repo itself
> Error in case of requested permissions are not granted

Just to confirm, this use case is to get extra privileges beyond those supplied by default with `GITHUB_TOKEN`?

> - some repos & no permissions
>    - token with intersection of all granted permissions for requested repos

I don't like this intersection logic, it's much too implicit and likely to break in strange ways. If you want to debug what permissions the token has, you have to go to every single target repo and look at the granted permissions for each, and then do an intersection. Say repo A has read access to repo B and C. If B stops giving read permissions, then suddenly A can no longer access C, even though **nothing** in A or C changed! A's CI starts to fail and you have no idea why.

I would say that if you have multiple repos, you have to list requested permissions explicitly. In the previous example, you would get an explicit error message when A requests B for read permissions, but is refused.

Do you see a case where explicitly listing permissions becomes burdensome? As I understand it, at most someone would need to list [the 13 permissions(https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) one time, right?

Once you go down this "must be explicit" path though, I might reconsider revisiting the `no repos & no permissions` case. I wouldn't like this inconsistency:

one repo -> permissions not required
2+ repos -> permissions required

To avoid this inconsistency, I would just make it so explicitly listing permissions are ALWAYS required.

So in summary, I might vote for:

> * **no repos & no permissions**
>   * => error
> * **no repos & some permissions**
>   * => token with requested permissions for requesting repo itself
>   * Error in case of requested permissions are not granted
> * **some repos & no permissions**
>   * -> error
> * **some repos & some permissions**
>   * => token with requested permissions for requested repos
>   * Error in case of requested permissions are not granted for all requested repos

This is all ignoring the fact that you might want different permissions for different repos. I'm not sure what the limitations are of the GitHub Actions `with:` syntax, but is this possible?

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/github-actions-access-manager@v1
        id: github-actions-access
        with:
          # everything under `with:` is a key-value arg, so we need a new
          # key different from `permissions` and `repository`
          per-repo:
             - repository: example/B
                permissions:
                 packages: read
             - repository: example/C
                permissions:
                  actions: write
```
