### ISSUE TITLE
FEAT: Request permissions using multiple blocks, also support `.github/access.yaml`

### ISSUE THREAD

**Issue by NickCrews** [qoomon/github-actions-access-manager#6]
We already configure which permissions are **granted** by a repo in `.github/access.yaml`

If https://github.com/qoomon/github-actions-access-manager/issues/4 is implemented, then the syntax for **requesting** permissions starts to get clunky. I think it would be nice to configure **both** the grants and requests in `.github/access.yaml`, and to follow the same syntax as for granting, with multiple `(repo, permissions)` blocks all ORed together.

```yaml
self: qoomon/example
# BREAKING, rename `policies` to `grants` (or similar)
grants:
- repository: octa-org/*
  permissions:
    packages: read
- repository: foo/bar
  permissions:
    issues: write
requests:
- repository: other-org/other-repo
  permissions:
    contents: read
- repository: user/*
  permissions:
    issues: read
```

One of the main benefits is that this now allows requesting permissions on a per-repo basis, and it allows consistent syntax.

For use cases where a repo only requests (ie doesn't give) permissions and the requested permissions are simple, then you should be able to inline this config in the workflow.yaml, to avoid needing an `access.yaml`:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: qoomon/github-actions-access-manager@v1
        id: github-actions-access
        with:
          # one option: if you just need a single block, then you could
          # unnest everything from the `requests` key, eg
          # repository: other-org/other-repo
          # permissions:
          #   contents: read
          requests:
            - repository: other-org/other-repo
              permissions:
                contents: read
            - repository: user/*
              permissions:
                issues: read
```
